# Generated by Django 4.2.6 on 2023-10-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Аpartments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("price", models.IntegerField(verbose_name="Цена")),
                ("adress", models.TextField(max_length=40, verbose_name="Адрес")),
                ("guests", models.IntegerField(verbose_name="Количество гостей")),
                ("beds", models.IntegerField(verbose_name="Количество спальныx мест")),
            ],
        ),
    ]
