# Generated by Django 4.2.6 on 2023-10-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="аpartments",
            options={"verbose_name": "Квартира", "verbose_name_plural": "Квартиры"},
        ),
    ]
