# Generated by Django 4.2.6 on 2023-10-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0002_alter_аpartments_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="аpartments",
            name="adress",
            field=models.CharField(max_length=40, verbose_name="Адрес"),
        ),
    ]
