# Generated by Django 4.2.6 on 2023-10-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0003_alter_аpartments_adress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="аpartments",
            options={
                "ordering": ["id"],
                "verbose_name": "Квартира",
                "verbose_name_plural": "Квартиры",
            },
        ),
        migrations.AddField(
            model_name="аpartments",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="my_first_app/photos",
                verbose_name="Фотография",
            ),
        ),
    ]
