# Generated by Django 4.2.6 on 2023-10-29 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("my_first_app", "0004_alter_аpartments_options_аpartments_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заявки"),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_first_app.аpartments",
                        verbose_name="Квартира",
                    ),
                ),
            ],
        ),
    ]
